---
version: '3'
networks:
  streamflow_streamflow: # Kafka's network
    external: true  
volumes:
  streamflow_streamflow:
    external: true    
services:
  consumer:
    networks:
      - streamflow_streamflow
    volumes:
      - streamflow_streamflow:/var/lib/consumer     
    restart: on-failure
    build:
      context: ./    
    ports:
      - 5002:5000