---
version: '3'
networks:
  streamflow: # Kafka's network
    external: true  
volumes:
  streamflow_streamflow:
    external: true      
services:
  transactions:
    networks:
      - streamflow
    volumes:
      - streamflow:/var/lib/transactions        
    restart: on-failure
    build:
      context: ./