---
version: '3'
networks:
  stream: # Kafka's network
    external: true  
volumes:
  stream:
    external: true      
services:
  rates:
    networks:
      - stream
    volumes:
      - stream:/var/lib/rates        
    restart: on-failure
    build:
      context: ./